# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Telegraph' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Telegraph
pod 'SQLite.swift', '~> 0.12.2'
pod 'Socket.IO-Client-Swift', '~> 16.0'


end
